services:
  - type: web
    name: safe-space-monitor
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app -k eventlet -w 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: RENDER
        value: true
      - key: DEBUG
        value: false
      - key: SESSION_SECRET
        generateValue: true